GET http://localhost:8080/api/employees
Accept: application/json

###

GET http://localhost:8080/api/employees/1
Accept: application/json

###
GET http://localhost:8080/api/employees/1
Accept: application/json
If-none-match: "3"

###

POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "Jane Doe"
}

### Update

PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
  "name": "Jane Doe 666"
}

### Delete

DELETE http://localhost:8080/api/employees/9